booktime/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from main import views
from main import models
from main import forms

urlpatterns = [
    path(
        "order/done/",
        TemplateView.as_view(template_name="order_done.html"),
        name="checkout_done",
    ),
    path(
        "order/address_select/",
        views.AddressSelectionView.as_view(),
        name="address_select",
    ),
    path('basket/', views.manage_basket, name="basket"),
    path(
        "add_to_basket/",
        views.add_to_basket,
        name="add_to_basket",
    ),
    path(
        "address/",
        views.AddressListView.as_view(template_name='address_list.html'),
        name="address_list",
    ),
    path(
        "address/create/",
        views.AddressCreateView.as_view(template_name="address_form.html"),
        name="address_create",
    ),
    path(
        "address/<int:pk>/",
        views.AddressUpdateView.as_view(template_name="address_update.html"),
        name="address_update",
    ),
    path(
        "address/<int:pk>/delete/",
        views.AddressDeleteView.as_view(
            template_name="address_confirm_delete.html"),
        name="address_delete",
    ),

    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="login.html",
            form_class=forms.AuthenticationForm,
        ),
        name="login",
    ),
    path(
        "signup/",
        views.SignupView.as_view(),
        name="signup"
    ),
    path(
        "product/<slug:slug>/",
        DetailView.as_view(model=models.Product,
                           template_name='product_detail.html'),
        name='product'
    ),
    path(
        'products/<slug:tag>/',
        views.ProductListView.as_view(),
        name='products',
    ),
    path(
        "contact-us/",
        views.ContactUsView.as_view(),
        name="contact_us"
    ),
    path(
        "about-us/",
        TemplateView.as_view(template_name="about_us.html"),
        name='about_us',
    ),
    path(
        '',
        TemplateView.as_view(template_name='home.html'),
        name='home',
    )
]

main/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractUser,
    BaseUserManager,
)
from django.core.validators import MinValueValidator
import logging

logger = logging.getLogger(__name__)


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        if extra_fields.get("is_staff") is not True:
            raise ValueError(
                "Superuser must have is_staff=True."
            )
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(
                "Superuser must have is_superuser=True."
            )
        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField('email address', unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()


class ProductTagManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class ProductTag(models.Model):
    objects = ProductTagManager()

    name = models.CharField(max_length=32)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.slug,)


class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class Product(models.Model):
    objects = ActiveManager()

    name = models.CharField(max_length=32)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    slug = models.SlugField(max_length=48)
    active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(ProductTag, blank=True)

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to="product-images")
    thumbnail = models.ImageField(
        upload_to="product-thumbnails", null=True
    )

    def __str__(self):
        return self.product.name


class Address(models.Model):
    SUPPORTED_COUNTRIES = (
        ("uk", "United Kingdom"),
        ("us", "United States of America"),
        ("ng", "Nigeria"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    address1 = models.CharField("Address line 1", max_length=60)
    address2 = models.CharField(
        "Address line 2", max_length=60, blank=True
    )
    zip_code = models.CharField(
        "ZIP / Postal code", max_length=12
    )
    city = models.CharField(max_length=60)
    country = models.CharField(
        max_length=3, choices=SUPPORTED_COUNTRIES
    )

    def __str__(self):
        return ", ".join(
            [
                self.name,
                self.address1,
                self.address2,
                self.zip_code,
                self.city,
                self.country,
            ]
        )


class Basket(models.Model):
    OPEN = 10
    SUBMITTED = 20
    STATUSES = ((OPEN, "Open"), (SUBMITTED, "Submitted"))

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True
    )
    status = models.IntegerField(choices=STATUSES, default=OPEN)

    def is_empty(self):
        return self.basketline_set.all().count() == 0

    def count(self):
        return sum(i.quantity for i in self.basketline_set.all())

    def create_order(self, billing_address, shipping_address):
        if not self.user:
            raise exceptions.BasketException(
                "Cannot create order without user"
            )
        logger.info(
            f"Creating order for basket_id={self.id}"
            ", shipping_address_id={shipping_address.id}, billing_address_id={billing_address.id}"
        )
        order_data = {
            "user": self.user,
            "billing_name": billing_address.name,
            "billing_address1": billing_address.address1,
            "billing_address2": billing_address.address2,
            "billing_zip_code": billing_address.zip_code,
            "billing_city": billing_address.city,
            "billing_country": billing_address.country,
            "shipping_name": shipping_address.name,
            "shipping_address1": shipping_address.address1,
            "shipping_address2": shipping_address.address2,
            "shipping_zip_code": shipping_address.zip_code,
            "shipping_city": shipping_address.city,
            "shipping_country": shipping_address.country,
        }
        order = Order.objects.create(**order_data)
        c = 0
        for line in self.basketline_set.all():
            for item in range(line.quantity):
                order_line_data = {
                    "order": order,
                    "product": line.product,
                }
                order_line = OrderLine.objects.create(
                    **order_line_data
                )
                c += 1
        logger.info(
            f"Created order with id={order.id} and lines_count={c}")
        self.status = Basket.SUBMITTED
        self.save()
        return order


class BasketLine(models.Model):
    basket = models.ForeignKey(Basket, on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE
    )
    quantity = models.PositiveIntegerField(
        default=1, validators=[MinValueValidator(1)]
    )


class Order(models.Model):
    NEW = 10
    PAID = 20
    DONE = 30
    STATUSES = ((NEW, "New"), (PAID, "Paid"), (DONE, "Done"))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUSES, default=NEW)
    billing_name = models.CharField(max_length=60)
    billing_address1 = models.CharField(max_length=60)
    billing_address2 = models.CharField(
        max_length=60, blank=True
    )
    billing_zip_code = models.CharField(max_length=12)
    billing_city = models.CharField(max_length=60)
    billing_country = models.CharField(max_length=3)
    shipping_name = models.CharField(max_length=60)
    shipping_address1 = models.CharField(max_length=60)
    shipping_address2 = models.CharField(
        max_length=60, blank=True
    )
    shipping_zip_code = models.CharField(max_length=12)
    shipping_city = models.CharField(max_length=60)
    shipping_country = models.CharField(max_length=3)
    date_updated = models.DateTimeField(auto_now=True)
    date_added = models.DateTimeField(auto_now_add=True)


class OrderLine(models.Model):
    NEW = 10
    PROCESSING = 20
    SENT = 30
    CANCELLED = 40
    STATUSES = (
        (NEW, "New"),
        (PROCESSING, "Processing"),
        (SENT, "Sent"),
        (CANCELLED, "Cancelled"),
    )
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="lines"
    )
    product = models.ForeignKey(
        Product, on_delete=models.PROTECT
    )
    status = models.IntegerField(choices=STATUSES, default=NEW)

main/forms.py
from django import forms
from django.core.mail import send_mail
import logging
from django.contrib.auth.forms import (
    UserCreationForm as DjangoUserCreationForm
)
from django.contrib.auth.forms import UsernameField
from django.contrib.auth import authenticate
from django.forms import inlineformset_factory
from . import models, widgets


logger = logging.getLogger(__name__)


BasketLineFormSet = inlineformset_factory(
    models.Basket,
    models.BasketLine,
    fields=("quantity",),
    extra=0,
    widgets={"quantity": widgets.PlusMinusNumberInput()},
)


class UserCreationForm(DjangoUserCreationForm):
    class Meta(DjangoUserCreationForm.Meta):
        model = models.User
        fields = ("email",)
        field_classes = {"email": UsernameField}

    def send_mail(self):
        logger.info(
            f"Sending signup email for email={self.cleaned_data['email']}"

        )
        message = f"Welcome {self.cleaned_data['email']}"
        send_mail(
            "Welcome to BookTime",
            message,
            "site@booktime.domain",
            [self.cleaned_data["email"]],
            fail_silently=True,
        )


class ContactForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    message = forms.CharField(max_length=600, widget=forms.Textarea)

    def send_mail(self):
        logger.info("Sending email to customer service")
        message = f"From: {self.cleaned_data['name']}\n{self.cleaned_data['message']}"
        send_mail(
            "Site message",
            message,
            'site@booktime.domain',
            ['customerservice@booktime.domain'],
            fail_silently=False
        )


class AuthenticationForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(
        strip=False, widget=forms.PasswordInput
    )

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        if email is not None and password:
            self.user = authenticate(
                self.request, email=email, password=password
            )
            if self.user is None:
                raise forms.ValidationError(
                    "Invalid email/password combination."
                )
            logger.info(
                "Authentication successful for email=%s", email
            )
        return self.cleaned_data

    def get_user(self):
        return self.user


class AddressSelectionForm(forms.Form):
    billing_address = forms.ModelChoiceField(
        queryset=None)
    shipping_address = forms.ModelChoiceField(
        queryset=None)

    def __init__(self, user, *args, **kwargs):
        super(). __init__(*args, **kwargs)
        queryset = models.Address.objects.filter(user=user)
        self.fields['billing_address'].queryset = queryset
        self.fields['shipping_address'].queryset = queryset

main/templates/about_us.html
{% extends "base.html" %}
{% block content %}
<h2>About us</h2>
<p>BookTime is a company that sells books online.</p>
{% endblock content %}

main/templates/address_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h2>Delete address</h2>
<form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete it?</p>
    <button type="submit" class="btn btn-­primary">Submit
    </button>
</form>
{% endblock content %}

main/templates/address_form.html
{% extends "base.html" %}
{% block content %}
<h2>Add a new address</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-­primary">Submit</button>
</form>
{% endblock content %}

main/templates/address_list.html
{% extends "base.html" %}
{% block content %}
<h1>List of your addresses:</h1>
{% for address in object_list %}
<p>
    {{ address.name }}<br>
    {{ address.address1 }}<br>
    {{ address.address2 }}<br>
    {{ address.city }}<br>
    {{ address.get_country_display }}<br>
</p>
<p>
    <a href="{% url "address_update" address.id %}">Update
        address</a>
</p>
<p>
    <a href="{% url "address_delete" address.id %}">Delete
        address</a>
</p>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
<p>
    <a href="{% url "address_create" %}">Add new address</a>
</p>
{% endblock content %}

main/templates/address_select.html
{% extends "base.html" %}
{% block content %}
<h2>Select the billing/shipping addresses</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-­primary">Submit</button>
    <a class="btn btn-primary" href="{% url "address_create"
%}">Add a new one</a>
</form>
{% endblock content %}

main/templates/address_update.html
{% extends "base.html" %}
{% block content %}
<h2>Add a new address</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-­primary">Submit</button>
</form>
{% endblock content %}

main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-­fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>BookTime</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-­light">
        <a class="navbar-brand" href="/">BookTime</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about-us/">About us</a>
                </li>
            </ul>
        </div>
    </nav>
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}


    {% block content %}
    {% endblock content %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block js %}
    {% endblock js %}
</body>

</html>

main/templates/contact_form.html
{% extends "base.html" %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        {{ form.name.label_tag }}
        <input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}" id="id_name" name="name" placeholder="Your name" value="{{ form.name.value|default:'' }}">
        {% if form.name.errors %}
        <div class="invalid-feedback">
            {{ form.name.errors }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.message.label_tag }}
        <textarea class="form-control {% if form.message.errors %}
        is-­invalid{% endif %}" id="id_message" name="message" rows="3">
        {{ form.message.value|default:""}}
        </textarea>
        {% if form.message.errors %}
        <div class="invalid-feedback">
            {{ form.message.errors }}
        </div>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock content %}

main/templates/home.html
{% extends "base.html" %}
{% block content %}
<h2>Home</h2>
<p>this will be the content of home</p>
{% endblock content %}

main/templates/login.html
{% extends "base.html" %}
{% block content %}
<h2>Login</h2>
<p>Please fill the form below.</p>
<form method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">
        {{ form.email.label_tag }}
        <input type="email" class="form-control {% if form.email.errors %}
is-­invalid{% endif %}" id="id_email" name="email" placeholder="Your email" value="{{ form.email.value|default:"" }}">
        {% if form.email.errors %}
        <div class="invalid-feedback">
            {{ form.email.errors }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.password.label_tag }}
        <input type="password" class="form-control{% if form.password.errors %}
is-­invalid{% endif %}" id="id_password" name="password" value="{{ form.password.value|default:"" }}">
        {% if form.password.errors %}
        <div class="invalid-feedback">
            {{ form.password.errors }}
        </div>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-­primary">Submit</button>
</form>
{% endblock content %}

main/templates/order_done.html
{% extends "base.html" %}
{% block content %}
<p>Thanks for your order.</p>
{% endblock content %}

main/templates/product_detail.html
{% extends "base.html" %}
{% block content %}
<h1>products</h1>
<table class="table">
    <tr>
        <th>Name</th>
        <td>{{ object.name }}</td>
    </tr>
    <tr>
        <th>Cover images</th>
        <td>
            <div id="imagebox">
                Loading...
            </div>
        </td>
    </tr>
    <tr>
        <th>Price</th>
        <td>{{ object.price }}</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>{{ object.description|linebreaks }}</td>
    </tr>
    <tr>
        <th>Tags</th>
        <td>{{ object.tags.all|join:"," | default:"No tags available" }}</td>
    </tr>
    <tr>
        <th>In stock</th>
        <td>{{ object.in_stock|yesno|capfirst }}</td>
    </tr>
    <tr>
        <th>Updated</th>
        <td>{{ object.date_updated|date:"F Y" }}</td>
    </tr>


</table>
<a href="{% url "add_to_basket" %}?product_id={{ object.id }}">
    Add to basket</a>

{% endblock content %}
{% block js %}
<script src="https://unpkg.com/react@16/umd/react.production.min.js">
</script>
<script src="https://unpkg.com/react-dom@16/umd/react-dom.production.
min.js">
</script>
<style type="text/css" media="screen">
    .image {
        margin: 10px;
        display: inline-block;
    }
</style>
<script>
    const e = React.createElement;
    class ImageBox extends React.Component {
        constructor(props) {
            super(props);
            this.state = {
                currentImage: this.props.imageStart
            }
        }
        click(image) {
            this.setState({
                currentImage: image
            });
        }

        render() {
            const images = this.props.images.map((i) =>
                e('div', {
                        className: "image",
                        key: i.id
                    },
                    e('img', {
                        onClick: this.click.bind(this, i),
                        width: "100",
                        src: i.thumbnail
                    }),
                ),
            );
            return e('div', {
                    className: "gallery"
                },
                e('div', {
                        className: "current-image"
                    },
                    e('img', {
                        src: this.state.currentImage.image
                    })
                ),
                images)
        }
    }
    document.addEventListener("DOMContentLoaded",
        function (event) {
            var images = [{% for image in object.productimage_set.all %} {
                    "image": "{{ image.image.url|safe }}",
                    "thumbnail": "{{ image.thumbnail.url|safe }}"
                },
                {% endfor %}
            ]
            ReactDOM.render(
                e(ImageBox, {
                    images: images,
                    imageStart: images[0]
                }),
                document.getElementById('imagebox')
            );
        });
</script>
{% endblock %}

main/templates/product_list.html
{% extends "base.html" %}
{% block content %}
<h1>Products</h1>
{% for product in page_obj %}
<p>{{ product.name }}</p>
<p>
    <a href="{% url 'product' product.slug %}">See it here</a>
</p>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
<nav>
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}">
                Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Previous</a>
        </li>
        {% endif %}
        {% for pagenum in page_obj.paginator.page_range %}
        <li class="page-item{% if page_obj.number == pagenum %}
active{% endif %}">
            <a class="page-link" href="?page={{pagenum}}">{{pagenum}}
            </a>
        </li>
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_
page_number}}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endblock content %}

main/templates/signup.html
{% extends "base.html" %}
{% block content %}
<h2>Sign up</h2>
<p>Please fill the form below.</p>
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        {{ form.email.label_tag }}
        <input type="email" class="form-control {% if form.email.errors %}
is-­invalid{% endif %}" id="id_email" name="email" placeholder="Your email" value="{{ form.email.value|default:"" }}">
        {% if form.email.errors %}
        <div class="invalid-feedback">
            {{ form.email.errors }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.password1.label_tag }}
        <input type="password" class="form-control {% if form.password1.errors %}
is-­invalid{% endif %}" id="id_password1" name="password1" value="{{ form.password1.value|default:"" }}">
        {% if form.password1.errors %}
        <div class="invalid-feedback">
            {{ form.password1.errors }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.password2.label_tag }}
        <input type="password" class="form-control{% if form.password2.errors %}
is-­invalid{% endif %}" id="id_password2" name="password2" value="{{ form.password2.value|default:"" }}">
        {% if form.password2.errors %}
        <div class="invalid-feedback">
            {{ form.password2.errors }}
        </div>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}